apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-new.fullname" . }}-backend
  labels:
    {{- include "app-new.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: backend
  selector:
    {{- include "app-new.selectorLabels" . | nindent 4 }}
---

