apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-new.fullname" . }}
  labels:
    {{- include "app-new.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app-new.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "app-new.fullname" . }}
    spec:
      containers:
        - name: {{ include "app-new.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: data
              mountPath: /app/backend/data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{ else }}{{ include "app-new.fullname" . }}-data{{ end }}
