apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app-new.fullname" . }}-pvc
  labels:
    {{- include "app-new.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.storageClass | default "gp3" }}
---

